### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by semisight** [Verfacto/gtm-verfacto-tracker#1]
https://github.com/Verfacto/gtm-verfacto-tracker/blob/e2fffd01099e980825ed835508ba1b87fb04ba78/template.tpl#L65

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by jekamth** [comment]
URL encoding was added with the latest template version
